# ==========================================================================
# CRE WORKFLOW SETTINGS — Morpho Vault Health
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "sdl-morpho-vault-health-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "sdl-morpho-vault-health-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
