module.exports = {
  apps: [
    {
      name: 'sentinel-ai',
      cwd: __dirname + '/platform',
      script: 'cre_analyze_endpoint.py',
      interpreter: __dirname + '/platform/.venv/bin/python',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 3000,
      max_memory_restart: '300M',
      env: {
        PYTHONUNBUFFERED: '1',
        PORT: '5060',
      },
    },
    {
      name: 'sentinel-dashboard',
      cwd: __dirname + '/dashboard',
      script: 'node_modules/.bin/next',
      args: 'start -p 3016',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 3000,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: '3016',
      },
    },
    {
      name: 'sentinel-tunnel',
      script: '/usr/local/bin/cloudflared',
      args: 'tunnel --config /home/avi/.cloudflared/sentinel-dashboard-tunnel.yml run',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'sentinel-ai-tunnel',
      script: '/usr/local/bin/cloudflared',
      args: 'tunnel --config /home/avi/.cloudflared/sentinel-ai-tunnel.yml run',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 10000,
      kill_timeout: 5000,
    },
  ],
};
