# ==========================================================================
# CRE WORKFLOW SETTINGS — stLINK Arb Monitor
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "stlink-arb-monitor-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "stlink-arb-monitor-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""
