# ==========================================================================
# CRE WORKFLOW SETTINGS — stLINK Arb Monitor
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "link-ai-arbitrage-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "link-ai-arbitrage-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: ""
